server:
  port: 8081

log:
  level: info

mysql:
  host: host.docker.internal
  port: 3306
  user: root
  password: ""
  database: wiki
  charset: utf8mb4
  max_idle_conns: 20
  max_open_conns: 200
  conn_max_lifetime: 7200

redis:
  host: host.docker.internal
  port: 6379
  password: ""
  db: 0

rag:
  index_name: wiki_vector_idx
  key_prefix: "doc:"
  vector_field: vector_content
  vector_dim: 3072
  vector_index_type: hnsw
  batch_size: 20
  default_top_k: 5
  max_top_k: 50
  hnsw_max_edges_per_node: 16
  hnsw_ef_construction: 200
  hnsw_ef_runtime: 10

job:
  log_db_level: info
